8: Добавить пайплайн очистки в CI
week-password/wlss-backend pull request #10
Opened 2023-04-09 09:53 UTC by birthdaysgift

После того как мы добавили линтеры в CI пайплайн с помощью GitHub Actions (#6), на вкладке [Actions](https://github.com/week-password/wisher-backend/actions) стали отображаться запущенные и завершенные раны нашего пайплайна. Так как мы используем ребейз-скваш флоу при работе с гитом, то очень часто будет возникать ситуация в которой ветка была запушена с хешами коммитов, например, "1" и "2", но потом ребейзнута, и хэши коммитов поменяются на "3" и "4". После этого у нас в нашем списке ранов на гитхабе останутся раны для коммитов "1" и "2". Но так как эти раны связаны с несуществующими на текующий момент коммитами, то нет смысла их хранить, т.к. они будут просто засорять список действительно полезных и нужных ранов для актуальных коммитов. Аналогичная ситуация будет происходить и при удалении веток - гитхаб будет хранить раны для коммитов в несуществующих ветках.

Удалять такие раны вручную и постоянно следить за этим довольно неудобно, поэтому в рамках настройки CI необходимо добавить воркфлоу, который будет автоматически удалять раны с гитхаба для несуществующих коммитов после ребейза ветки и после удаления ветки.

2023-04-10 08:26 UTC, Rey-Lane requested changes

2023-04-10 08:26 UTC, Rey-Lane commented on .github/workflows/cleanup.yml
> +          python-version: "3.10"
Почему тут `Python 3.10`?

2023-04-10 08:26 UTC, Rey-Lane commented on envs/ci/scripts/github/cleanup/runs/rebased_branch.py
> +        yield commit_hash
Может это сделать как-то более безопасно?

```python
def get_branch_commits():
    repository = Github(GITHUB_TOKEN).get_repo(GITHUB_REPOSITORY)
    current_branch = repo.get_branch(GITHUB_REF_NAME)
    base_branch = repo.get_branch("develop")
    commits_diff = repo.compare(base_branch.commit.sha, current_branch.commit.sha)
    for commit in compare.commits:
        yield commit.sha
```
Не ручаюсь за работоспособность этого кода, примерный план

2023-04-10 09:27 UTC, birthdaysgift commented on .github/workflows/cleanup.yml
> +          python-version: "3.10"
По большому счету нет разницы какой тут пайтон, т.к. единственное его предназначение это выполнить cleanup-скрипт, а с этой задачей справится и 3.5)

Но вообще, если мы можем использовать последний пайтон, то почему бы его не использовать. Да и к тому же я уже обновил 3.10 -> 3.11 в предыдущей джобе, а здесь забыл

2023-04-10 09:36 UTC, Rey-Lane commented on .github/workflows/cleanup.yml
> +          python-version: "3.10"
Логика рассуждений понятна)
Просто, как говорится, `подоконник либо вровень, либо выпирает` 😅

2023-04-10 09:45 UTC, birthdaysgift commented on envs/ci/scripts/github/cleanup/runs/rebased_branch.py
> +        yield commit_hash
Да, так лучше, и всё работает)

2023-04-10 10:11 UTC, Rey-Lane approved these changes

2023-04-10 10:15 UTC, merged

2023-04-21 19:58 UTC, birthdaysgift commented
Коммит, на который ссылается пулл реквест не существует, так как мы меняли соглашение по именованию коммитов и ребейзили `develop` ветку. Подробнее об этом можно почитать в [обсуджении](https://github.com/week-password/wisher-backend/discussions/3#discussioncomment-5640598).

Хэш нового коммита, содержащего точную копию изменений внесённых этим пулл-реквестом: 4a3402a4