15: Добавить юнит-тесты в CI
week-password/wlss-backend pull request #16
Opened 2023-04-10 10:45 UTC by birthdaysgift

После того как мы настроили окружение для юнит-тестов (#14), необходимо сразу добавить их в CI-пайплайн, что все последующие мр-ы проходили тесты через CI.

В рамках этой задачи необходимо:

- добавить сервис для запуска pytest в `envs/ci/docker-compose.yml`
- добавить новый воркфлоу `.github/workflows/test.yml`, который будет запускать пайтест по аналогии с запуском линтеров в `.github/workflows/lint.yml`

2023-04-10 11:02 UTC, Rey-Lane requested changes

2023-04-10 11:02 UTC, Rey-Lane commented on .github/workflows/test.yml
> +  mypy:
`mypy`
Накопировал)

2023-04-10 14:26 UTC, Rey-Lane approved these changes

2023-04-10 14:28 UTC, merged

2023-04-21 20:01 UTC, birthdaysgift commented
Коммит, на который ссылается пулл реквест не существует, так как мы меняли соглашение по именованию коммитов и ребейзили `develop` ветку. Подробнее об этом можно почитать в [обсуджении](https://github.com/week-password/wisher-backend/discussions/3#discussioncomment-5640598).

Хэш нового коммита, содержащего точную копию изменений внесённых этим пулл-реквестом: f68c3321