1: Add git user setup script
week-password/wlss-backend pull request #2
Opened 2023-02-19 00:15 UTC by birthdaysgift

### Проблема
Так как разработчик может работать с разными репозиториями на одной машине одновременно, то может возникнуть ситуация, когда он коммитит в репозиторий не под тем аккаунтом. Например, если на машине разработчика в глобальных настройках гита указан рабочий имейл, то когда он будет коммитить в какой-то опенсорс или пет репозиторий, то его коммиты будут подписываться его рабочим имейлом - хотя он возможно этого не хотел. Или если разработчик работает с одним и тем же проектом, но на разных машинах, то может возникнуть ситуация, когда коммиты одного и того же разработчика подписываются по разному в зависимости от того с какой машины он коммитит.

Не все поймут, не многие вспомнят, но наверняка каждый хоть раз встречался с такими коммитами:
![image](https://user-images.githubusercontent.com/35929293/219904870-78ee3fbc-d9b3-4484-8849-179354c10b9d.png)
Довольно неприятная ситуация, когда ты работаешь в распределенной команде и  понятие не имеешь, кто сделал коммит.

Неправильно настроенные данные для гит репозитория могут выстрелить в ногу (не сильно больно, но неприятно) в самый неожиданный момент. Например, разработчик может заметить, что его коммиты почему-то не отображаются в статистике гитхаба, хотя он регулярно коммитит в репозитории. Это связано с тем, что гитхаб не может сопоставить имейл из коммита и имейл аккаунта гитхаба, т.к. они различаются. Если бы разработчик изначально сконфигурировал свой гит так, чтобы в коммиты записывался его гитхабовский имейл, то такой проблемы бы не возникло.

Наверняка можно найти и другие проблемы, к которым приводит неправильно сконфигурированные данные в гите.

### Решение
Подобных ситуаций можно избежать, если для каждого репозитория указать имя и имейл в локальном файле `.git/config`. Но для того чтобы разработчикам не нужно было запоминать в какой файл и что именно нужно писать, можно создать баш скрипт, который будет делать это за него. Это позволит разработчикам легко настраивать гит под наш проект и при этом не изменять свои глобальные конфигурации.

### В рамках задачи необходимо:
- добавить баш скрипт, который спрашивает у пользователя имя и имейл и добавляет их в конец файла `.git/config`

2023-02-19 12:17 UTC, Rey-Lane requested changes

2023-02-19 12:17 UTC, Rey-Lane commented on envs/dev/scripts/git/iam.sh
> +read name
Хотелось бы добавить больше гибкости и избежать ситуаций, что ленивый разработчик просто скипнет эту стадию путём нажатия Enter. Тогда получится, что в конфиг запишется пустота, чего не хотелось бы. Можно добавить пару условий, например:

```
if [[ -z "${name// }" ]]; then
    echo "Error: 'name' can not be empty"
    exit 1
fi
```
Проводим проверку на то, что строка пустая. И на то, что в строке только пробелы.

2023-02-20 06:27 UTC, Rey-Lane requested changes

2023-02-20 06:27 UTC, Rey-Lane commented on envs/dev/scripts/git/iam.py
> +PROJECT_ROOT = Path(__file__).parent.parent.parent.parent.parent
Может лучше так:
`PROJECT_ROOT = Path(__file__).parents[4]`

2023-02-20 06:27 UTC, Rey-Lane commented on envs/dev/scripts/git/iam.py
> +    config["user"]["email"] = email
Может стоит объединить эти две функции? Кажется маловероятным, что у нас может разделиться логика обновления имени пользователя и его почты, это просто параметры конфига. Думаю нет смысла держать 2 большие функции, которые отличаются только сообщением.

Можно как-то так сделать, например:
```
def update_config_field(config_object, key, asking_message):
   if key in config["user"]:
       print(f"\nYour config already has {key} = {config['user'][key]}")

    answer = input("Do you want to rewrite it? (y/n):\n")
    while answer not in ["y", "n"]:
        answer = input("\nUnknown command, only y/n are acceptable:\n")
     if answer == "n":
            return

    value = input(asking_message).strip()
    while not value:
        print(f"{key.title()} cannot be empty")
        value = input(asking_message).strip()

    config["user"][key] = value
 ```

А в функции `main()` вызывать обновление как-то так:
```
# init config blah blah blah
update_config_field(config_obj, "name", "Enter the name ...")
update_config_field(config_obj, "email", "Enter the email ...")
```

2023-02-25 15:24 UTC, birthdaysgift commented on envs/dev/scripts/git/iam.py
> +    config["user"]["email"] = email
В общем посмотрел я на этот пайтон скрипт, и че-то мне вообще расхотелось так заморачиваться. Я решил что не нужно добавлять какого-то функционала сверху, типа проверки на то, что эти значения уже есть в конфиге. По идее нам нужно сделать очень тонкую обертку над двумя командами
```bash
git config user.name "John Doe"
git config user.email "john@mail.com"
```
У этой обертки всего две цели:
1. Объяснить пользователю зачем это вообще нужно и что происходит.
2. Помочь ему с вводом команд - вместо комманд, он будет сразу писать те значения, которые нужны.

И кажется для этой задачи вполне подходит баш. При этом совершенно необязательно делать проверку на то пустая строка или нет, потому что после того как пустая строка запишется в конфиг и пользователь попытается что-то закоммитить, гит всё равно скажет ему типа "ты кто такой я тебя не знаю".

2023-02-25 15:24 UTC, birthdaysgift commented on envs/dev/scripts/git/iam.py
> +PROJECT_ROOT = Path(__file__).parent.parent.parent.parent.parent
Да. это гениально, почему мы раньше так не делали)

2023-02-26 05:00 UTC, Rey-Lane commented on envs/dev/scripts/git/iam.py
> +PROJECT_ROOT = Path(__file__).parent.parent.parent.parent.parent
Небольшое количество `parent` ещё имеет место быть)
А вот 5 подряд уже многовато)

2023-02-27 21:45 UTC, birthdaysgift commented on envs/dev/scripts/git/iam.sh
> +read name
в другом [комменте](https://github.com/week-password/wisher-backend/pull/2/files#r1117938319) написал, что кажется нет смысла над этим заморачиваться

2023-02-28 06:16 UTC, Rey-Lane commented on envs/dev/scripts/git/iam.sh
> +SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
^ Кажется, что это не нужно

2023-02-28 06:18 UTC, Rey-Lane requested changes
Необходимо убрать инициализацию переменной `SCRIPT_DIR` в `bash`скрипте и удалить `.py` файл

2023-02-28 16:13 UTC, birthdaysgift commented on envs/dev/scripts/git/iam.sh
> +SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
эт нужно, просто я забыл его использовать)

Мы же когда вызываем `git config` то он работает только на тот репозиторий откуда вызван. И если например кто-то зачем-то будет вызывать этот скрипт из другого репозитория (даже не спрашивай меня зачем), то юзер будет конфигурироваться в другой репе.

Поправил в последнем коммите

2023-03-01 07:45 UTC, Rey-Lane requested changes
Нужно обсудить рамки действия скрипта

2023-03-01 07:45 UTC, Rey-Lane commented on envs/dev/scripts/git/iam.sh
> +SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
Кажется это оверинжениринг уже)

Хочешь сделать такой скрипт в новом репозитории - скопируй скрипт и запусти. 
Тут нет сложной логики, дублирование скрипта в другой репозиторий не привнесёт никаких затруднений, учитывая, что его используют только один раз при развёртке окружения.

Если придёт другой разработчик, скажем, в команду фронта? Ему, чтобы запустить скрипт, нужно будет спуллить бек? Зато удобно, один скрипт работает на все репозитории))
 
Можно придумать много кейсов использования и оправдать их: а если этот скрипт будет использован во время прыжка на парашюте, или верхом на коне? Но здесь, кажется, можно обойтись и без всего этого, на мой взгляд.

2023-03-01 10:22 UTC, birthdaysgift commented on envs/dev/scripts/git/iam.sh
> +SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
> если кто-то будет вызывать этот скрипт из другого репозитория, то юзер будет конфигурироваться в другой репе.

я как раз пытаюсь избежать ситуации, которую описал ^

я хочу чтобы скрипт всегда конфигурировал юзера только в том проекте, где этот скрипт лежит и не важно откуда он при этом вызывается

2023-03-02 07:45 UTC, Rey-Lane commented on envs/dev/scripts/git/iam.sh
> +SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
Нужен созвон по этому вопросу

2023-03-02 12:44 UTC, Rey-Lane approved these changes

2023-03-02 12:45 UTC, merged

2023-04-21 19:55 UTC, birthdaysgift commented
Коммит, на который ссылается пулл реквест не существует, так как мы меняли соглашение по именованию коммитов и ребейзили `develop` ветку. Подробнее об этом можно почитать в [обсуджении](https://github.com/week-password/wisher-backend/discussions/3#discussioncomment-5640598).

Хэш нового коммита, содержащего точную копию изменений внесённых этим пулл-реквестом: e48ed06d