21: Добавить FastAPI
week-password/wlss-backend pull request #24
Opened 2023-04-13 14:21 UTC by Rey-Lane

Необходимо добавить в проект основной фреймворк для разработки - FastAPI. Для проверки корректности его работы необходимо добавить простой эндпоинт - healthcheck. Помимо этого необходимо заложить базовую структуру приложения.

2023-04-13 23:12 UTC, birthdaysgift requested changes

2023-04-13 23:12 UTC, birthdaysgift commented on pyproject.toml
> +fastapi = {extras = ["all"], version = "0.95.0"}  # We use extras = ["all"] because fastapi TestClient requers some additional dependencies
Чтобы коммент не выходил за 120 символов его можно немного перефразировать:
```python
# We use "all" here because fastapi TestClient doesn't work without it
```

2023-04-13 23:12 UTC, birthdaysgift commented on pyproject.toml
> +fastapi = "0.95.0"
Да, мне бы тоже хотелось оставить пайтон на самом верху и не сортировать его алфавитно вместе с библиотеками проекта, но давай тогда отделим его от остальных зависимостей визуально, тип такого:
```toml
[tool.poetry.dependencies]

python = "~3.11"

fastapi = "0.95.0"
psycopg-binary = "1.2.3"
sqlalchemy = "4.5.6"
```

2023-04-13 23:12 UTC, birthdaysgift commented on tests/test_service/test_healthcheck.py
> +def test_healthcheck():
Насколько я знаю, тесты тоже нужно сделать асинхронными. Пока не совсем понимаю зачем это делать, но в доке fastapi есть такой [раздел](https://fastapi.tiangolo.com/advanced/async-tests/).

Возможно нам еще пригодится [pytest-asyncio](https://pypi.org/project/pytest-asyncio/), но пока не уверен...

UPD: pytest-asyncio не нужен, потому что при установке `fastapi[all]` ставится `anyio`, и, кажется, он позволяет делать асинхронные тесты через `@pytest.mark.anyio`

PS: Судя по всему `TestClient` также придётся заменить на `AsyncClient` из `httpx`.

2023-04-13 23:12 UTC, birthdaysgift commented on src/app.py
> +from fastapi import FastAPI
Предлагаю договориться выделять блок всех импортов одной пустой строкой сверху и двумя снизу, т.е.:
```python
"""Docstring."""

from fastapi import FastAPI

from src.routes import router


app = FastAPI()
app.include_router()
```
Одна пустая строка перед списком импортов будет визуально отделять их от докстринга. А две строки после импортов будут отделять их от остального кода. Если возникает вопрос, почему именно две строки, а не одна, то это для того чтобы отличать разделитель перед кодом от разделителя между группами импортов. Группы импортов отделяются друг от друга одной линией, а импорты от кода - двумя.

Так же предлагаю сразу договориться о расположении и содержании блока `if TYPE_CHECKING:`. Предлагаю писать этот блок после всех импортов, и отделять его одной строчкой сверху. Импорты внутри блока писать по тем же правилам, что и снаружи, т.е. сначала системные модули, потом сторонние, и потом модули приложения. Каждая группа отделяется одной строкой, все импорты отсортированы в алфавитном порядке.

Таким образом полный пример будет выглядеть как-то так:

```python
"""Docstring."""

from typing import TYPE_CHECKING

from fastapi import FastAPI

from src.routes import router

if TYPE_CHECKING:
    from typing import Iterable

    from fastapi import HTTPException

    from src.models import User
    from src.utils import pretty_print


app = FastAPI()
app.include_router()
```

К сожалению линтеры, это не проверяют, поэтому придётся об этом договориться и следить за этим своими силами (ну либо написать плагин флейку и перейти на флейк, если есть желание :smile: ).

Если апрувим такой подход, то могу зафиксировать это в вики бэкенда.

2023-04-13 23:12 UTC, birthdaysgift commented on src/app.py
> +"""Main fastAPI application."""
Предлагаю сделать либо `fastapi`, либо `FastAPI`.

А то какой-то странный подоконник получается : )

2023-04-13 23:27 UTC, birthdaysgift commented
Также есть ряд вопросов, которые не были освещены в ревью, т.к. я пока сам до конца не уверен, как сделать лучше. Над этим надо подумать и принять решение.

1. Т.к. судя по всему healthcheck роут не будет удалён, а станет частью системы, и будет действительно использоваться для проверки состояния приложения, то надо бы решить куда его положить. Пока что у нас два варианта - тот который сейчас, т.е. в папке `service` ("обслуживание", в смысле техническое) или в своей папке `healthcheck`.
2. Меня смущает использование названия сервиса непосредственно в коде приложения, т.е. в `src`. Боюсь что это вызовет трудности при ребрендинге (хотя, конечно, понятно, что ребрендинг и так вызовет трудности в случае чего). Кажется, что можно везде слово "wisher" заменить на "app", без какой-либо потери смысла с точки зрения исходного кода проекта.
3. Немного смущает нейминг роутеров. Мне кажется, что все роутеры лучше просто называть `router`. По аналогии с блюпринтами `bp` и неймспейсами `ns`. Кажется нет смысла писать, допустим, `user_router` если этот роутер и так лежит в `src.user.routes`. Разделение кода по пакетам привязанным к фиче как раз-таки позволяет нам в некоторых моментах упрощать нейминг. Например, если схема для кредов юзера лежит в `src.user.schemas` то её можно назвать просто `Credentials`, а не `UserCredentialsSchema`.

2023-04-14 08:50 UTC, Rey-Lane commented on src/app.py
> +from fastapi import FastAPI
Тут ruff ругался на двойной отступ после импортов, поэтому здесь не стал делать

2023-04-18 01:54 UTC, birthdaysgift approved these changes

2023-04-18 01:55 UTC, merged

2023-04-21 20:03 UTC, birthdaysgift commented
Коммит, на который ссылается пулл реквест не существует, так как мы меняли соглашение по именованию коммитов и ребейзили `develop` ветку. Подробнее об этом можно почитать в [обсуджении](https://github.com/week-password/wisher-backend/discussions/3#discussioncomment-5640598).

Хэш нового коммита, содержащего точную копию изменений внесённых этим пулл-реквестом: 847a4d99