Добавить PostgreSQL (#29)
week-password/wlss-backend pull request #46
Opened 2023-05-12 18:03 UTC by birthdaysgift

Так как мы планируем хранить наши данные в PostgreSQL, то необходимо добавить базовую конфигурацию постгреса для разработки, тестов и CI. Подключить sqlalchemy, настроить alembic и миграции. Создать моковую модель и написать два простеньких эндпойнта, один из которых будет создавать сущность в бд, а другой получать её по айди. Написать тесты к этим эндпойнтам и убедиться, что они работают локально и на CI.

В рамках этой задачи необходимо:

**Настройка окружениий**

- настроить бд для работы в трёх различных окружениях - `envs/local/dev`, `envs/local/test` и `envs/ci/test` для каждой конфигурации необходимо добавить `docker-compose.yml` с описанием контейнеров и `.env` файл с описанием необходимых переменных окружения

**Настройка БД, ORM, миграций**

- добавить параметры соединения с бд в `src/config.py` предлагаю не добавлять в конфиг значения по умолчанию, а создать механизм, который позволил бы явно указывать окружение для каждой выполняемой команды, например с помощью переменной окружения `WLSS_ENV`

- добавить `sqlalchemy`, `alembic` и драйвер для постгреса скорее всего для асинхронной работы вместо `psycopg-binary` нам нужно будет взять `asyncpg`

- проинициализировать асинхронные `engine`, `session` и `Base`, необходимые для работы алхимии, в `src/shared/database.py`

- проинициализировать и настроить алембик в папке `migrations` по дефолту он ставится в папку `alembic`, но команда `alembic init` позволяет передать другое имя директории также алембик предлагает разные [темплейты](https://alembic.sqlalchemy.org/en/latest/tutorial.html#creating-an-environment) для бд, скорее всего нам нужен будет `async`

- настроить коннекшн алембика с бд через опцию конфигурации `sqlalchemy.url` в `migrations/env.py`

- настроить коннекшн алембика с алхимией через переменную `target_metadata` в `migrations/env.py`

- настроить конфиг `alembic.ini` под нужды проекта пока что наши нужды это префикс даты и времени в GMT+0 для каждой миграции, чтобы они были отсортированы по дате создания

- добавить в алембик возможность явно указывать путь до файлов с моделями, чтобы они были проинициализированы до начала выполнения миграций

- добавить полезные для автогенерации миграций опции перечисленные [здесь](https://pytest-alembic.readthedocs.io/en/latest/setup.html#optional-but-helpful-additions), а именно - `compare_type=True, compare_server_default=True, include_schemas=True`

- добавить `disable_existing_loggers=False` для логгера алембика, как описано [здесь](https://pytest-alembic.readthedocs.io/en/latest/setup.html#caplog-issues) это позволит нам использовать фикстуру `caplog` в тестах в которых запускается алембик (например stairway-тесты для миграций)

- подключить `black` к алембику для форматирования файлов миграций

**Добавление моделей, миграций, эндпойнтов**

- добавить временную модель `Entity` с одним полем `id` для проверки работоспособности бд

- создать и применить миграции

- добавить два роута в `src/entity/routes.py` - один для создания объекта `Entity`, другой для его получения из бд по айди

**Добавление тестов**

- добавить тесты для созданных роутов

- добавить stairway-тесты для миграций есть плагин [pytest-alembic](https://pypi.org/project/pytest-alembic/), который вроде как может сделать это за нас UPD: с pytest-alembic возник ряд проблем, которые возможно даже являются багами этой либы, поэтому решили пока не добавлять. Более подробно о возникших проблемах можно почитать в комментариях к этому тикету (#29).

**Обновление README.md**

- добавить информацию о применении миграций в раздел `First time setup` здесь должна быть описана только команда `alembic upgrade head` более подробная инфа по работе с миграциями будет в отдельном разделе

- описать процесс запуска докер контейнеров в разделе `Run Application`

- добавить информацию о процессе настройки окружения и запуске докер контейнеров для тестирования в раздел `Run tests`

- добавить раздел `Working with migrations` перед разделом `Troubleshooting`, в котором описать пока что основные способы работы с миграциями: создание миграций, апгрейд и даунгрейд

2023-05-12 18:06 UTC, birthdaysgift commented
Для одной задачи работы получилось многовато, но зато это позволило разработать новый подход с минимумом переделок уже существующего кода. На основе этого мр-а в следующий раз, когда понадобится добавить postgres в каком-то другом проекте, можно будет создать более мелко декомпозированные задачи, которые будут в изначально направлены на реализацию идей из этой задачи.

2023-05-12 18:09 UTC, birthdaysgift commented on .github/workflows/test.yml
> +        run: docker compose --file envs/ci/test/docker-compose.yml up --attach pytest --exit-code-from pytest
Это позволяет запустить нам всю пачку контейнеров из компоуз файла, и автоматически уничтожить их, после того как сервис пайтеста отработает.

2023-05-12 18:16 UTC, birthdaysgift commented on .mypy.ini
> +plugins = pydantic.mypy
Плагин чтобы подружить пайдэнтик и майпай. В [доках](https://docs.pydantic.dev/latest/mypy_plugin/) можно почитать подробное описане для чего он нужен.

Конкретно в нашем случае пришлось его добавить, т.к. майпай не распознавал аттрибуты класса конфигурации при вызове инита:

```python

class Config(BaseSettings):
    foo: int
    bar: int

config = Config()  # вот тут майпай давал ошибку, что типа init требует два позиционных аргумента
```

2023-05-12 18:21 UTC, birthdaysgift commented on .pylintrc
> +extension-pkg-whitelist=pydantic
В комментарии выше попытался указать причину для чего это нужно, хотя на самом деле так до конца и не понял. Проблема была в том, что пайлинт ругался на импорты из пайдантика, например:
```python
from pydantic import BaseModel  # вот тут пайлинт утверждает что BaseModel нет в пакете pydantic
```

Возможно это связано с тем, что часть пайдантика написана на СИ (хотя я совсем в этом не уверен). Потому что на сколько я понимаю пайлинт даёт такие ошибки для либ, часть которых написана на си, потому что не может распознать сишные модули.

2023-05-12 18:26 UTC, birthdaysgift commented on .pylintrc
> +    pylint_per_file_ignores,  # This pylint plugin will enable per-file-ignores in your project
Тут прямо вообще грусть печаль, потому что во-первых пайлинт не умеет исключать конкретные ошибки в конкретных файлах с помощью конфигурации (ну типа как у нас сделано для тестов в `.flake8`), а во вторых, даже после подключения этого плагина, оказывается, что он умеет читать `per-file-ignores` конфигурацию только из `.toml` файлов, поэтому засунуть его в `.pylintrc` не получится.

***

Хоть мы и планировали в `pyproject.toml` хранить только, но тут всё равно пришлось добавить туда параметр для пайлинта.

2023-05-12 18:38 UTC, birthdaysgift commented on alembic.ini
> +    src.entity.models,
Сюда будут прописываться пути до моделей, чтобы алембик их учитывал при генерировании миграций.

В файле `migrations/env.py` есть код, который отвечает за парсинг этой опции и импорт всех моделей перечисленных здесь до того как алембик начнёт работать с миграциями.

2023-05-12 18:40 UTC, birthdaysgift commented on alembic.ini
> +hooks = black,check_empty_migration
Регистрируем два хука - `black` для автоматического форматирования кода сгенерированных миграций, `check_empty_migration` для предупреждения пользователя о том что была создана пустая миграция

2023-05-12 19:01 UTC, birthdaysgift commented on src/shared/database.py
> +    """Base class for models."""
Решил сделать через наследование, т.к. при старом подходе `Base = declarative_base()` майпай не понимает что происходит и начинает ругаться

2023-05-12 19:03 UTC, birthdaysgift commented on src/shared/database.py
> +            await session.close()
Не уверен обязательно ли закрывать сессию, ведь по идее мы используем `scoped_session`, которая вроде как умеет менеджить сама себя.

Но т.к. вроде раньше этот нормально работал, то не стал тратить время на ресёрч и оставил так :D

2023-05-12 19:06 UTC, birthdaysgift commented on src/shared/utils/environment.py
До сих пор не уверен куда положить этот файл - то ли оставить как есть сейчас, т.е. в `src/shared/utils/environment.py` то ли просто в `src/shared/environment.py`. Кажется нет смысла создавать папку utils ведь у нас есть shared, где по идее должно храниться всё, что шарится разными частями приложения.

2023-05-13 12:05 UTC, birthdaysgift commented on src/shared/utils/environment.py
Всё таки решил положить его просто в `src/shared`.

2023-05-14 10:02 UTC, Rey-Lane requested changes

2023-05-14 10:02 UTC, Rey-Lane commented on migrations/env.py
> +        compare_type=True,
Этот `compare_type` распространится на все типы миграций? Просто раньше мы прописывали его и в `online` и в `offline`.

2023-05-14 10:02 UTC, Rey-Lane commented on migrations/env.py
> +        importlib.import_module(module_path)
Может тут `try/except` добавить? А то мало ли что понапишут в этом `models_packages`

2023-05-14 10:02 UTC, Rey-Lane commented on src/entity/models.py
> +
Может быть на будущее подумать про несколько базовых миксинов для моделей? По типу миксина, который добавляет поле `id`, миксина, который добавляет временные метки (`created_at, updated_at`), чтобы потом не прописывать одинаковые поля в каждой модели?

По типу
```python
class MyModel(IdMixin, DateMixin):
    # only model necessary fields
```

2023-05-14 10:02 UTC, Rey-Lane commented on src/shared/environment.py
> +    """Raised if there were errors during environment variables loading."""
Мы точно хотим это исключение держать здесь? Найдём ли мы его потом, в случае чего?)

2023-05-14 10:02 UTC, Rey-Lane commented on README.md
> +- Downgrade certain number of migrations
Line should end with a period

2023-05-14 10:02 UTC, Rey-Lane commented on README.md
> +WLSS_ENV=local/test pytest --cov=src --cov-context=test --envfile=envs/local/test/.env ; coverage html --show-contexts --no-skip-covered
Эта строка у меня не работает
![image](https://github.com/week-password/wisher-backend/assets/65604613/90569a55-c99e-4d35-bee1-3629e7b68655)

2023-05-14 12:30 UTC, birthdaysgift commented on README.md
> +- Downgrade certain number of migrations
Fixed

2023-05-14 12:38 UTC, birthdaysgift commented on src/shared/environment.py
> +    """Raised if there were errors during environment variables loading."""
Думаю найдём. Эксепшн относится к ошибкам энвариномента и определён в модуле, в котором лежат вещи для работы с энвайронментом.

Если ты предлагаешь положить его в `src/exceptions.py`, то это получится package by layer, а хотелось бы соблюдать package by feature.

Ну если это сильно смущает, то можно сделать так:
```text
src/
    shared/
        environment/
            __init__.py
            environment.py
            exceptions.py
```
получится package by layered feture, что тоже неплохо. Но в таком случае я не знаю как назвать модуль с функциями, потому что `environment.environment` получается как-то неочень.

2023-05-14 12:40 UTC, birthdaysgift commented on src/entity/models.py
> +
Скорее всего в будущем у нас появится еще базовый класс, который будет предоставлять универсальный `.get()` по айди. Но возможно стоит сделать это в другом мр-е, а то тут и так уже дофига кода)

А ещё эти миксины надо бы хорошенько продумать, потому что у меня есть несколько вопросов по ним. И кажется этот ресерч точно стоит перенести в другой тикет.

2023-05-14 12:41 UTC, birthdaysgift commented on migrations/env.py
> +        importlib.import_module(module_path)
Согласен, добавил.

2023-05-14 12:42 UTC, birthdaysgift commented on migrations/env.py
> +        compare_type=True,
До сих пор неочень понимаю чем отличается online и offline. Какой-то странный нейминг, не могли что ли нормально назвать)

В общем, на всякий случай добавил в online тоже. Для подстраховки :laughing:

2023-05-14 12:43 UTC, birthdaysgift commented on README.md
> +WLSS_ENV=local/test pytest --cov=src --cov-context=test --envfile=envs/local/test/.env ; coverage html --show-contexts --no-skip-covered
Круто, что заметил. Да, это я забыл убрать `--envfile` после экспериментов. Теперь он неактуален, поэтому выпилил его.

Сейчас эта команда должна работать

2023-05-14 12:44 UTC, birthdaysgift commented on .github/workflows/lint.yml
> +  black:
Добавил проверку форматирования миграций блэком на CI. Потому что хук срабатывает только в момент генерации алембиком, и если кто-то потом будет редактировать миграцию руками, то может забыть вызвать блэк после этого.

2023-05-14 12:45 UTC, birthdaysgift commented on README.md
> +```
Добавил команду запуска блэка на миграциях на случай, когда миграции редактируются руками.

2023-05-14 12:45 UTC, birthdaysgift commented on envs/ci/lint/docker-compose.yml
> +    entrypoint: black --line-length=120 --check migrations
Добавил контейнер с блэком для проверки форматирования миграций на CI.

2023-05-15 06:53 UTC, Rey-Lane approved these changes
Подумай над исключениями и `utils` в `shared/environment`. Если пока не уверен, то можешь вливать. Если понравилась идея с `utils` или `env_utils`, то можешь переделать и потом вливать)

2023-05-15 06:53 UTC, Rey-Lane commented on src/shared/environment.py
> +    """Raised if there were errors during environment variables loading."""
Я и имел ввиду второй вариант)
Чтобы ответить на второй вопрос достаточно прочитать докстринг к этому файлу: `"""Utilities for working with environment variables."""` -> `utils` или `env_utils`

2023-05-15 06:53 UTC, Rey-Lane commented on src/entity/models.py
> +
Вместо базового класса можно подумать над репозиториями))

2023-05-15 16:17 UTC, birthdaysgift commented on src/entity/models.py
> +
Т.к. у нас пока что нет глубокого понимание как работать с DDD Репозиториями, решили с пока что сделать по старинке, а после релиза MVP заняться рефакторингом и в рамках него попробовать добавить DDD репозитории.

Оставил об этом заметку в [бэклоге бэклога](https://github.com/week-password/wisher-backend/wiki/%D0%97%D0%B0%D0%B4%D0%B0%D1%87%D0%B8.-%D0%91%D1%8D%D0%BA%D0%BB%D0%BE%D0%B3-%D0%B1%D1%8D%D0%BA%D0%BB%D0%BE%D0%B3%D0%B0).

Полезная ссылка, которая может пригодиться:
https://dddinpython.com/index.php/2022/11/09/implementing-the-repository-pattern-using-sqlalchemy/

2023-05-15 17:55 UTC, birthdaysgift commented on src/shared/environment.py
> +    """Raised if there were errors during environment variables loading."""
Ну вообще в таком варианте меня смущают оба имени - и `utils` и `exceptions`.

`utils` смущает потому, что, во-первых, такое название по большому счёту не добавляет никакого смысла, а, во-вторых, не понятно почему функции считаются uility, а эксепшены нет.

`exceptions` смущает потому, что файл объединяет штуки на уровне языка. Например всякие пакеты типа `routes`, `models` и `schemas`, объединяют вещи на уровне фреймворка, и это выглядит чуть более осмыслено. Потому что если мы например продолжим использовать идею лежашую в основе вынесения эксепшенов в `exceptions`, то нам придётся также создавать модули типа `functions` и `classess`.

***

Возможно стоило бы порефакторить пакеты с помощью добавления паблик штук в `__init__.py` пакета. В таком случае теоретически можно будет не так сильно задумываться над неймингом модулей внутри пакета. Да и вообще выделение паблик интерфейса для пакета, кажется неплохой идеей.

***

В общем, я довольно долго думал над тем как разнести модули по пакетам и понял, что на данном этапе трудно предвидеть и учесть многие нюансы, которые возникнут потом. Поэтому кажется лучше сначала написать какую-то часть приложения, а потом провести рефакторинг с учётом уже имеющихся связей в кодовой базе.

Оставил заметку в [бэклоге бэклога](https://github.com/week-password/wisher-backend/wiki/%D0%97%D0%B0%D0%B4%D0%B0%D1%87%D0%B8.-%D0%91%D1%8D%D0%BA%D0%BB%D0%BE%D0%B3-%D0%B1%D1%8D%D0%BA%D0%BB%D0%BE%D0%B3%D0%B0), чтобы не забыть.

2023-05-15 17:58 UTC, merged