5: Добавить и настроить линтеры
week-password/wlss-backend pull request #7
Opened 2023-04-06 15:33 UTC by birthdaysgift

Так как мы хотим, чтобы любой код, попадающий в репозиторий сразу проверялся линтерами, необходимо в первую очередь добавить и настроить все линтеры, которые мы планируем использовать в проекте. А именно: `mypy`, `ruff`, `flake8`, `pylint`.

Т.к. мы будем использовать несколько линтеров, и некоторые линтеры имеют схожие проверки, то во время настройки линтеров необходимо учесть это и отключить похожие проверки в тех линтерах, которые работают дольше. Линтеры в порядке скорости их работы, от самого быстрого к самому медленному:

1. ruff
2. flake8
3. pylint

Также необходимо решить какие плагины мы будем использовать для [флейка](ссылка), [пайлинта](ссылка) и, возможно, раффа. При этом стоит учесть, что некоторые плагины могут быть отключены по умолчанию, и недостаточно просто добавить их, но надо также явно активировать их.

Для всех плагинов необходимо просмотреть список проверок, которые они выполняют и по аналогичной схеме описанной выше, отключить те из них, которые работают с более медленным линтером.

Для добавления пакетов линтеров в репозиторий необходимо будет пользоваться пакетным менеджером. В качестве пакетного менеджера было решено использовать `poetry`. И т.к. poetry настраивается через pyptoject.toml, может появится желание положить настройки всех линтеров туда же, но пока что мы решили не смешивать все конфигурации в одном файле. Поэтому конфигурации линтеров должны быть в своих соответствующих .ini/.rc файлах.

При установке и настройке poetry для проекта, возникнет вопрос - какую версию Python использовать? Было принято решение использовать самую последнюю версию python, которая доступна на данный момент - 3.11.

Все линтеры должны быть установлены в dev-группу зависимостей poetry.

Также необходимо зафиксировать в README.md порядок запуска линтеров:

1. mypy
2. ruff
3. flake8
4. pylint

Этот порядок обсуловлен тем, что сначала необходимо с помощью майпая проверить код на наличие багов и несоответствий типов, т.к. эти ошибки сложнее всего пофиксить. После этого необходимо запустить рафф, чтобы получить быструю обратную связь, т.к. рафф работает быстрее всех линтеров. Затем флейком проверить оставшиеся проблемы в коде, и в конце запустить самый долгий линтер - пайлинт. В идеале можно было бы поискать способ как запускать их всех параллельно, но в таком случае также надо будет решить проблему того, что все эти линтеры будут одновременно писать свой аутпут в консоль и смешаются друг с другом.

В рамках текущей задачи необходимо:

- настроить локальное окружение для разработки с использованием `poetry`
- добавить в `README.md` инструкцию по разворачиванию локального окружения для разработки
- добавить и настроить `mypy`, `ruff`, `flake8`, `pylint` и плагины к ним
- добавить в `README.md` инструкцию по запуску линтеров

2023-04-07 08:43 UTC, Rey-Lane requested changes

2023-04-07 08:43 UTC, Rey-Lane commented on .pylintrc
> +    type,
`pragma: no cover` не подходит под этот игнор?

2023-04-07 08:43 UTC, Rey-Lane commented on .pylintrc
> +spelling-ignore-words=
Это похоже на `whitelist.txt`, или я ошибаюсь? Если да, то можно оставить что-то одно

2023-04-07 08:43 UTC, Rey-Lane commented on .ruff.toml
Видел, что `ruff` реализовал функционал плагина `flake8-quotes`. Двойные кавычки указаны по умолчанию? Или их нужно явно указать? Или это учитывается где-то в другом конфиге?

2023-04-07 10:28 UTC, birthdaysgift commented on .pylintrc
> +spelling-ignore-words=
Да, это практически одно и то же. В пайлинте есть свой спеллчекер, они не могут полностью заменить друг друга. Вот таблица, в которой написано какой спеллчек, что проверяет:

| Header | flake8 | pylint |
|--------|--------|--------|
| докстринги | - | + |
| переменные | + | - |
| комменты | + | + | 

Т.е. придётся оставить оба, потому что иначе нам придётся отказаться от проверки либо докстрингов либо переменных.

Но есть и хорошая новость - мне удалось подключить наш вайтлист от флейка к спеллчекеру пайлинта с помощью: 
```ini
[SPELLING]
spelling-private-dict-file=whitelist.txt
```
Так что теперь у нас будет только один вайтлист на оба спеллчекера.

***

PS Для того чтобы спеллчекер пайлинта работал, необходимо дополнительно установить [pyenchant](https://pypi.org/project/pyenchant/), а также в конфиге прописать словарь:
```ini
[SPELLING]
spelling-dict=en_US
```
В прошлый раз я это забыл, так что добавил сейчас.

2023-04-07 10:28 UTC, birthdaysgift commented on .pylintrc
> +    type,
Подходит, добавил.

2023-04-07 10:32 UTC, birthdaysgift commented on .ruff.toml
Да, во флейке по дефолту почему-то были одиночные... Рафф сделал по дефолту двойные, и теперь рафф нравится мне еще больше :laughing:

2023-04-07 10:38 UTC, birthdaysgift commented on .pylintrc
> +    type,
Только почему-то не работает :confused:

2023-04-07 13:50 UTC, Rey-Lane requested changes

2023-04-07 13:50 UTC, Rey-Lane commented on pyproject.toml
> +python = "3.11.2"
Предлагаю установить версию Python 3.11.1, так как для тех, кто использует `pyenv` 3.11.2 ещё не релизнулась. Хотя на официальном сайте уже есть 3.11.3))

2023-04-07 13:50 UTC, Rey-Lane commented on .pylintrc
> +spelling-dict = en_US
Установка этого параметра ломает работу `pylint` на `macOS`. Получается следующая ошибка:
```pylint: error: argument --spelling-dict: invalid choice: 'en_US' (choose from '')```
Без неё всё работает

2023-04-07 13:53 UTC, birthdaysgift commented on .pylintrc
> +spelling-dict = en_US
> Без неё всё работает
Скорее всего это потому что спеллчекер вообще не запускается.

[Здесь](https://stackoverflow.com/a/27162411/8431075) для мака советуют поставить enchant на уровне системы.
Возможно [это](https://stackoverflow.com/a/73052239/8431075) поможет.

2023-04-07 14:00 UTC, Rey-Lane commented on .pylintrc
> +spelling-dict = en_US
Действительно, Apple-silicon как обычно голову морочит. Вторая ссылка помогла)

2023-04-07 14:01 UTC, birthdaysgift commented on pyproject.toml
> +python = "3.11.2"
Я ставил python через `apt-get` и он автоматически берет последнюю минорную, поэтому я не могу даунгрейднуться до 3.11.1) Если есть идеи как это можно сделать, то я готов попробовать)

Вообще, думаю между ними нет сильных различий, поэтому можно зафиксировать 3.11.2 и просто подождать когда она выдет для `pyenv`, а до этого работать на 3.11.1.

2023-04-07 14:06 UTC, Rey-Lane commented on pyproject.toml
> +python = "3.11.2"
Твоя версия будет работать, если прописать `>= 3.11.2`. Я не думаю, что в рамках этого проекта различия между версиями 3.11.1 и 3.11.2 могут стрельнуть нам в ногу

2023-04-07 15:37 UTC, birthdaysgift commented on .pylintrc
> +spelling-dict = en_US
Добавил решение в README.md

2023-04-07 15:57 UTC, birthdaysgift commented on pyproject.toml
> +python = "3.11.2"
`^3.11.1` будет использовать все версии до 4-го пайтона, т.е. `3.11`, `3.12`, и тд. ([дока](https://python-poetry.org/docs/dependency-specification/#caret-requirements))

Если мы хотим менять только патч версию, то нужно использовать что-то из этого:
- `~3.11.0` или `~3.11` ([дока](https://python-poetry.org/docs/dependency-specification/#tilde-requirements))
- `3.11.*` ([дока](https://python-poetry.org/docs/dependency-specification/#wildcard-requirements))

***

Кажется, действительно с фиксированием патч-версии много возни, поэтому предлагаю просто зафиксировать минорную версию `3.11`, а патч пускай будет любой. Если это стрельнет нам в ногу, то будем думать, как это зафиксировать, а пока думаю и так сойдёт...

<img src="https://user-images.githubusercontent.com/35929293/230638712-4101ff04-1b1a-42ad-ae0d-2632b268a929.png" height="350">

2023-04-07 20:30 UTC, Rey-Lane commented on pyproject.toml
> +python = "3.11.2"
Да, доку я читал, с решением согласен 😅

2023-04-08 08:03 UTC, Rey-Lane approved these changes

2023-04-08 10:41 UTC, merged

2023-04-21 19:56 UTC, birthdaysgift commented
Коммит, на который ссылается пулл реквест не существует, так как мы меняли соглашение по именованию коммитов и ребейзили `develop` ветку. Подробнее об этом можно почитать в [обсуджении](https://github.com/week-password/wisher-backend/discussions/3#discussioncomment-5640598).

Хэш нового коммита, содержащего точную копию изменений внесённых этим пулл-реквестом: afa0f44f